### ISSUE TITLE
Calls are blocking

### ISSUE THREAD

**Issue by trevoriancox** [piwik/piwik-python-api#16]
I don't see any mention of this library being non-blocking. Typically one wouldn't want the analytics to slow down the website. e.g. I currently use segment.com's analytics python client which is non-blocking: https://segment.com/docs/libraries/python/.

**Comment by brendoncrawford** [comment]
This would be a nice feature, but I don't expect that I will have the time to implement this.  If anyone wants to, they could integrate on of these:
- https://github.com/kennethreitz/grequests
- https://github.com/ross/requests-futures
