### ISSUE TITLE
Mark project as unmaintained

### ISSUE THREAD

**Issue by nkuttler** [piwik/piwik-python-api#17]
Due to github not allowing me to reopen #13 I open a new issue, because I won't be able to dedicate the necessary time to maintain this project.

Actually, I'd suggest a complete rewrite. It was my first API, it's a mess, it's modeled after the PHP tracking class and as such it's not pythonic.

Thanks for all the support from Piwik HQ.

**Comment by brendoncrawford** [comment]
Hi @nkuttler , @mattab : 

I am interested in maintaining this project. Is this proper place to make this request?

Thanks

**Comment by brendoncrawford** [comment]
If anyone is interested, for now, I am maintaining a fork here, which I intend to keep up to date:
https://github.com/brendoncrawford-org/piwik-python-api
